server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #配置git仓库地址
          uri: https://github.com/forezp/SpringcloudConfig/
          #配置仓库路径
          search-paths: respo
          #访问git仓库的用户名
          username: chenjincan111
          #访问git仓库的用户名
          password: cjc205310251
      #配置仓库的分支
      label: master
